name: 'build'

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          docker build . --tag ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}
